### ISSUE TITLE
Rename to switch-map-operator

### ISSUE THREAD

**Issue by Andarist** [fasiha/callbag-flat-map-operator#1]
Actually this is a `switchMap` and not a `flatMap`. Unfortunately `callbag-switch-map` is taken and broken, so you should republish this as `callbag-switch-map-operator`. 

As to `flatMap` - somebody need to reimplement it or build `flattenConcurrently` on top of which `flatMap` could be built.

Reference - https://github.com/staltz/callbag-flatten/pull/2/files

**Comment by fasiha** [comment]
Thanks for reaching out!

Is the switchmap/flatmap difference you're talking about the same as Rx? I'm reading e.g.
- https://www.learnrxjs.io/operators/transformation/mergemap.html on flatmap and
- https://www.learnrxjs.io/operators/transformation/switchmap.html on switchmap and
- http://reactivex.io/documentation/operators/flatmap.html (which surprisingly doesn't include function signatures 😡?)

to get a sense of how these differ and wanted to make sure that was the convention you're talking about.

**Comment by Andarist** [comment]
Yeah, Rx conventions are most known so the rest should (imho) align naming with them to avoid confusion. `flatMap` is an alias for `mergeMap`. I think you were looking into general Rx docs (which is language independent, so maybe that's why there are no signatures there) - for a RxJS reference you can look [here](http://reactivex.io/rxjs/class/es6/Observable.js~Observable.html#instance-method-mergeMap).

Difference between `flatMap` & `switchMap` is easy (probably u already know that, going to continue explanation for completness):
- `flatMap` - subscribes to each inner observable and "flattens" the stream
- `switchMap`/`flatMapLatest` - subscribes only to the latest inner observable and "flatten" the stream

In `xstream` equivalents are:
- `flatMap` -> `map` + `flattenConcurrently`
- `switchMap` -> `map` + `flatten`
- `concatMap` -> `map` + `flattenSequentially`

**Comment by fasiha** [comment]
I haven’t forgotten about this!, just swamped with work and will get to this soon. I’m trying to make sure I understand the difference between switchmap and flatmap, and whether the different only matters for listenable or both pullables/listenables, and in either case my implementation actually does cancel the earlier callbag (which is my main confusion, I don’t think it does but need to do more experimentation). I definitely want to help the callbag community so thanks for your patience and for your stewardship!

**Comment by Andarist** [comment]
friendly 🏓

**Comment by fasiha** [comment]
Thank you for following up, and for helping take care of the callbag community 🙇‍♂️!!! Your ping motivated me to prove to myself that this repo is indeed switchMap and not flatMap and here's the proof:
```js
var flatmap = require('./');
var { pipe, forEach, interval, take } = require('callbag-basics'); // npm i callbag-basics

pipe(
    interval(2500),
    flatmap(int => take(5)(interval(100)), (int, num) => [int, num]),
    take(10),
    forEach(x => console.log(x)),
);
/* you'll see 
[ 0, 0 ]
[ 0, 1 ]
[ 0, 2 ]
[ 0, 3 ]
[ 0, 4 ]
[ 1, 0 ]
[ 1, 1 ]
[ 1, 2 ]
[ 1, 3 ]
[ 1, 4 ]

But,
*/

pipe(
    interval(250),
    flatmap(int => take(5)(interval(100)), (int, num) => [int, num]),
    take(10),
    forEach(x => console.log(x)),
);
/*
But now, the inner interval (100 ms) is switched when the outer (250 ms) interval fires.
[ 0, 0 ]
[ 0, 1 ]
[ 1, 0 ]
[ 1, 1 ]
[ 2, 0 ]
[ 2, 1 ]
[ 3, 0 ]
[ 3, 1 ]
[ 4, 0 ]
[ 4, 1 ]
*/
```
